### ISSUE TITLE
client_secret in history

### ISSUE THREAD

**Issue by joey-kilgore** [mrjoeboo123/HylandHack2019#10]
Has the token that is saved in an old commit been refreshed on the google developer site? It looks like Jared accidentally commited his client_secret file and then removed it along with adding it to the gitignore. But is that client_secret still valid? If it is, it needs to be changed immediately.

**Comment by jared-maki** [comment]
I deleted the compromised token on the google dev site and then generated a new one after I realized I screwed up and uploaded the key. I'm sorry I should've communicated the incident with you guys at the hackathon

**Comment by joey-kilgore** [comment]
No problem, just wanted to make sure you didn't get hacked!
