### ISSUE TITLE
Remove __pycache__

### ISSUE THREAD

**Issue by joey-kilgore** [mrjoeboo123/HylandHack2019#12]
This folder has cache file for when python is interpreted to byte code, which is then executed by Python's virtual machine. [Check HERE for more info](https://stackoverflow.com/questions/2998215/if-python-is-interpreted-what-are-pyc-files)  
In the end, this folder should be deleted, and then *.pyc should be added to the .gitignore so that these files are not included moving forward.

**Comment by joey-kilgore** [comment]
Looks like this is finished up right?

**Comment by jared-maki** [comment]
Yeah it should be all finished up
